# Generated by Django 4.2.2 on 2023-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
