# Generated by Django 4.2.2 on 2023-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_urunler_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='renk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='isim',
            field=models.CharField(max_length=100),
        ),
    ]
