# Generated by Django 4.2.2 on 2023-07-21 13:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_urunler_renk_alter_urunler_isim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mesaj', ckeditor.fields.RichTextField()),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='urunler.urunler')),
            ],
        ),
    ]
