# Generated by Django 4.2.2 on 2023-07-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_remove_yorum_urun_yorum_date_added_alter_yorum_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='urun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='urunler.urunler'),
            preserve_default=False,
        ),
    ]
