# Generated by Django 4.2.2 on 2023-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_yorum_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorum',
            name='email',
            field=models.TextField(max_length=100),
        ),
    ]
